version: '3.1'
services:
  crudapp:
    container_name: crud_app
    image: adpalgar24/crud
    restart: always
    environment:
      DB_HOST: mariadb_crud
      DB_NAME: crud
      DB_USER: admin
      DB_PASSWORD: admin
    ports:
      - 9082:80
    depends_on:
      - db
  db:
    container_name: mariadb_crud
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: crud
      MARIADB_USER: admin
      MARIADB_PASSWORD: admin
    volumes:
      - mariadb_data_crud:/var/lib/mysql
volumes:
    mariadb_data_crud:
